# Generated by Django 4.1.1 on 2022-09-06 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'ID Number'), (2, 'Passport'), (3, 'Alien ID')], unique=True)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_detail',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('SasaPay', 'SasaPay')], max_length=100, null=True, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_cash_payment', models.SmallIntegerField(default=0, null=True)),
                ('order_position', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='TransactionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=255, null=True)),
                ('customer_mobile', models.CharField(max_length=255, null=True)),
                ('business_short_code', models.CharField(max_length=255, null=True)),
                ('invoice_number', models.CharField(max_length=255, null=True)),
                ('payment_method', models.CharField(max_length=255, null=True)),
                ('trans_id', models.CharField(max_length=255, null=True)),
                ('third_party_trans_id', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('transaction_type', models.CharField(max_length=255, null=True)),
                ('msisdn', models.CharField(max_length=255, null=True)),
                ('org_account_balance', models.CharField(max_length=255, null=True)),
                ('trans_amount', models.CharField(max_length=255, null=True)),
                ('trans_time', models.CharField(max_length=255, null=True)),
                ('bill_ref_number', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'transaction_notification',
            },
        ),
        migrations.CreateModel(
            name='WaasAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=255)),
                ('aml_score', models.IntegerField()),
                ('customer_account_number', models.CharField(max_length=255)),
                ('customer_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cumulative_points', models.DecimalField(decimal_places=2, max_digits=19)),
                ('redeemed_points', models.DecimalField(decimal_places=2, max_digits=19)),
                ('available_points', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cumulative_spent_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waas.documenttype')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waas_account',
            },
        ),
        migrations.CreateModel(
            name='WaasAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(max_length=12)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('transaction_type_enum', models.SmallIntegerField(choices=[(1, 'Transaction In'), (2, 'Transaction Out')])),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('points', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_code', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waas.waasaccount')),
                ('payment_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waas.paymentdetail')),
            ],
            options={
                'db_table': 'waas_account_transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=100, null=True)),
                ('checkout_request_id', models.CharField(max_length=255, null=True)),
                ('network_code', models.CharField(max_length=8, null=True)),
                ('sender_account_number', models.CharField(max_length=50, null=True)),
                ('recipient_account_number', models.CharField(max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('points', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('merchant_code', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100, null=True)),
                ('result_description', models.CharField(max_length=255, null=True)),
                ('transaction_type_enum', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('callback_url', models.URLField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('waas_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waas.waasaccount')),
            ],
            options={
                'db_table': 'transaction_staging',
            },
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waas.paymenttype'),
        ),
    ]
